org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
jei_version=15.20.0.124
jade_id=324717
jade_file_id=5339264
irons_spells_id=855414
irons_spells_file_id=7551870
caelus_version=3.2.0+1.20.1
curios_version=5.14.1+1.20.1
player-animation_version=1.0.2-rc1+1.20
curios_version_range=[1.20.1-5.12.1,)

forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mc_mapping_channel=official
mc_mapping_version=1.20.1
mod_id=calamity_curios
mod_name=CalamityCurios
mod_license=MIT
mod_version=1.20.1-1.1-beta
mod_group_id=hua223.calamity
mod_authors=hua223
mod_description=This mod ported some curios items from the Terraria Calamity
