package hua223.calamity.generators;

import hua223.calamity.register.effects.CalamityEffects;
import hua223.calamity.register.entity.CalamityEntity;
import hua223.calamity.register.gui.SpellType;
import hua223.calamity.register.keys.ClientInteraction;
import hua223.calamity.register.sounds.CalamitySounds;
import hua223.calamity.register.tab.CreateTab;
import hua223.calamity.util.CMLangUtil;
import net.minecraft.data.DataGenerator;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.common.data.LanguageProvider;

import static hua223.calamity.main.CalamityCurios.MODID;
import static hua223.calamity.register.Items.CalamityItems.*;
import static hua223.calamity.util.CMLangUtil.*;

@OnlyIn(Dist.CLIENT)
public class ModLangGen extends LanguageProvider {
    public ModLangGen(DataGenerator gen, String locale) {
        super(gen, MODID, locale);
    }

    //JSON Text Create
    @Override
    protected void addTranslations() {
        add(groupKey(CreateTab.CALAMITY_ITEM), "灾厄物品");
        add(groupKey(CreateTab.CALAMITY_CURIOS), "灾厄饰品");
        add(ZENITH.get(), "天顶剑");
        add(getCommonText("zenith"), "世界的顶点，超越无极之剑");
        add(YHARIM_GIFT.get(), "寻神者之礼");
        add(getCommonText("yharim_gift", 1), "装备后提升15 + 当前10%的防御");
        add(getCommonText("yharim_gift", 2), "受到伤害后你的无敌时间翻倍，燃火流星将会从天而降，且有概率向攻击者施加龙焰减益");
        add(getCommonText("yharim_gift", 3), "若你存在2个及以上的减益时，你的下一次受击会将减益效果移除至一个");
        add(CalamityEffects.DRAGON_BURN.get(), "龙焰");
        add(CalamityEffects.ASTRAL_INFECTION.get(), "幻星感染");
        add(RADIANCE.get(), "辐辉");
        add(getCommonText("radiance", 1), "一块曾经腐烂的水晶，现在闪烁着无瑕的纯净");
        add(getCommonText("radiance", 2), "增加70%最大生命值， 获得+1HP/5s生命再生");
        add(getCommonText("radiance", 3), "受到减益时再额外获得+1HP/5s生命再生");
        add(getCommonText("radiance", 4), "站立不动时获得每1.5s + 2HP/5s(最大20)生命再生");
        add(getCommonText("radiance", 5), "受到减益时会获得20点防御，除首个减益外的每个减益会额外提供8点防御");
        add(getCommonText("radiance", 6), "每存在一个减益+1HP/5s生命再生");
        add(getCommonText("radiance", 7), "无效化绝大部分减益");
        add(BLOODY_WORM_TOOTH.get(), "血蠕虫之牙");
        add(COUNTER_SCARF.get(), "反击围巾");
        add(EVASION_SCARF.get(), "闪避围巾");
        add(getCommonText("scarf", 1), "按下冲刺按键进行冲刺，该效果有10s的冷却");
        add(getCommonText("scarf", 2), "受伤到伤害时闪避此次攻击，该效果有30s的冷却");
        add(BLOODY_WORM_SCARF.get(), "血蠕虫围巾");
        add(getCommonText("worm_scarf"), "减免10%受到的伤害(伤害加成不与血蠕虫之牙叠加)");
        add(HIDE_OF_ASTRUM_DEUS.get(), "星神隐壳");
        add(getCommonText("hide", 1), "你的血肉正在被幻星熔蚀");
        add(getCommonText("hide", 2), "受到伤害或造成近战伤害时会令许多幻星从天而降");
        add(getCommonText("hide", 3), "受到伤害后产生一次爆炸并增加30%近战伤害, 增幅的持续时间基于你受到的伤害值，至多持续10秒");
        add(getCommonText("hide", 4), "使你免疫幻星感染、诅咒狱火、心火和霜冻减益");
        add(getCommonText("hide", 5), "攻击你的敌人也会受到伤害并且会受到幻星感染减益");
        add(WARBANNER_SUN.get(), "炎阳战旗");
        add(getCommonText("warbanner", 1), "祝你的战意如这烈阳般热烈");
        add(getCommonText("warbanner", 2), "当你接近敌人时会增加攻击力、近战伤害和攻击攻速");
        add(getCommonText("warbanner", 3), "至多增加20%攻击力、近战伤害和攻击攻速");
        add(BADGE_BRAVERY.get(), "勇气勋章");
        add(getAttribute("close_critical_strike_chance"), "近战暴击率");
        add(getAttribute("far_critical_strike_chance"), "远程暴击率");
        add(getAttribute("armor_penetrate"), "护甲穿透");
        add(CalamityEffects.ELEMENTAL_MIX.get(), "元素谐鸣");
        add(ELEMENTAL_GAUNTLET.get(), "元素之握");
        add(getCommonText("elemental_gauntlet", 1), "你的手中存在着异样的光辉");
        add(getCommonText("elemental_gauntlet", 2), "攻击会造成元素谐鸣减益");
        add(NIHILITY_QUIVER.get(), "虚无箭袋");
        add(getCommonText("nihility_quiver", 1), "充满比夜空更暗的物质");
        add(getCommonText("nihility_quiver", 2), "箭矢会提高75%的伤害且速度翻倍");
        add(CalamityEffects.IRRADIATED.get(), "辐射");
        add(getCommonText("rusty", 1), "让大多数远程武器攻击时在空中释放酸性液滴");
        add(getCommonText("rusty", 2), "使你免疫辐射减益");
        add(RUSTY_MEDALLION.get(), "锈蚀勋章");
        add(CalamityEntity.FIRE_METEOR.get(), "燃火流星");
        add(CalamityEntity.METEOR.get(), "幻星");
        add(CalamityEntity.ACIDIC_RAIN.get(), "酸液滴");
        add(CalamityEntity.ZENITH_PROJECTILE.get(), "天顶剑刃");
        add(getAttribute("far_attack"), "远程伤害");
        add(getAttribute("ammunition_add"), "减少弹药消耗");
        add(DEADSHOT_BROOCH.get(), "神射手胸针");
        add(DAAWNLIGHT.get(), "曙旼始灵");
        add(getCommonText("daawnlight", 1), "一缕失落宇宙的残烬，久久等待着她的御主");
        add(getCommonText("daawnlight", 2), "远程暴击率不再生效，取而代之的是击中生物的眉心时必定暴击且造成更高的暴击");
        add(getCommonText("daawnlight", 3), "基于你的远程暴击率百分比加成暴击伤害");
        add(CalamityEffects.ELECTRIFIED.get(), "带电");
        add(STEM_CELLS.get(), "痴愚金龙干细胞");
        add(getCommonText("stem_cells", 1), "狂暴，无序，混乱，盲目痴愚");
        add(getCommonText("stem_cells", 2), "使你免疫龙焰和带电减益");
        add(getCommonText("stem_cells", 3), "发射弹射物时有几率额外发射迷你龙裔，存在25s的冷却");
        add(CalamityEntity.MINI_DRAGON.get(), "癫狂龙裔");
        add(ELEMENTAL_QUIVER.get(), "魔法箭袋");
        add(getCommonText("deadshot_brooch"), "增加所有远程弹射物的速度");
        add(CalamityEffects.FREEZE.get(), "冰固");
        add(getAttribute("injury_offset"), "免伤");
        add(CONCOCTION.get(), "永冻秘药");
        add(getCommonText("concoction", 1), "增加50点最大魔力值并降低15%魔力消耗");
        add(getCommonText("concoction", 2), "低于50%生命值时+0.5HP/5s生命再生，低于25%生命值时+1HP/5s生命再生，低于10%生命值时+2HP/5s生命再生");
        add(getCommonText("concoction", 3), "着火时+3HP/5s生命再生");
        add(getCommonText("concoction", 4), "受到致死伤害时会复活并将生命值回复至40%，此效果有3分钟冷却");
        add(COMET_SHARD.get(), "彗星碎片");
        add(ETHEREAL_CORE.get(), "飘渺星核");
        add(PHANTOM_HEART.get(), "幻影之心");
        add(MANA_POLARIZER.get(), "魔能谐振仪");
        add(getCommonText("mana_polarizer", 1), "增加50点最大魔力值和10%魔法伤害");
        add(getCommonText("mana_polarizer", 2), "当前魔力值高于最大魔力值的50%时每20秒受到5%的最大生命值伤害");
        add(getCommonText("mana_polarizer", 3), "你的魔法伤害会回复生命，你的当前魔力值越高，你的吸血量便越高");
        add(CalamityEffects.MANA_BURN.get(), "魔力烧蚀");
        add(CalamityEffects.MANA_SICKNESS.get(), "魔力疾病");
        add(ENCHANTED_STARFISH.get(), "魔力星鱼");
        add(WEAK_MANA_POTION.get(), "弱效魔力药水");
        add(MANA_POTION.get(), "魔力药水");
        add(STRONG_MANA_POTION.get(), "强效魔力药水");
        add(SUPER_MANA_POTION.get(), "超级魔力药水");
        add(SUPREME_MANA_POTION.get(), "至尊魔力药水");
        add(CHAOS_STONE.get(), "混乱石");
        add(getCommonText("chaos_stone", 1), "远古遗物之一");
        add(getCommonText("chaos_stone", 2), "饮用魔力药水时会使你获得魔力烧蚀减益而非魔力疾病减益");
        add(getCommonText("chaos_stone", 3), "魔力烧蚀会持续对你造成伤害，伤害与减益的时间相关");
        add(getCommonText("chaos_stone", 4), "此减益不会降低你的魔法伤害");
        add(CALAMITY_SIGIL.get(), "灾厄符章");
        add(getCommonText("sigil", 1), "增加15%魔法伤害并降低10%魔力消耗");
        add(getCommonText("sigil", 2), "增加100点最大魔力值");
        add(ETHEREAL_TALISMAN.get(), "空灵护符");
        add(getCommonText("talisman", 1), "它似乎并不存在");
        add(getCommonText("talisman", 2), "增加15%魔法伤害、5%近战与远程暴击率");
        add(getCommonText("talisman", 3), "增加150点最大魔力值并降低10%魔力消耗");
        add(getCommonText("talisman", 4), "你会在需要时自动饮用魔力药水，右键此物品以关闭或开启");
        add(getCommonText("talisman", 5), "自动饮用已关闭");
        add(getCommonText("talisman", 6), "自动饮用已开启");
        add(CRAW_CARAPACE.get(), "蟹爪壳");
        add(getCommonText("craw"), "击中你的敌怪会受到伤害以及粉碎减益");
        add(CalamityEffects.CRUMBLING.get(), "粉碎");
        add(CalamityEffects.CURSED_INFERNO.get(), "狱火");
        add(ABYSSAL_AMULET.get(), "深渊护身符");
        add(getCommonText("abyssal", 1), "使你免疫激流与凋零减益，攻击会造成激流减益");
        add(getCommonText("abyssal", 2), "处于下界时增加10%最大生命值");
        add(CalamityEffects.RIPTIDE.get(), "激流");
        add(ROTTEN_BRAIN.get(), "腐烂之脑");
        add(getCommonText("rotten", 1), "生命值低于75%时增加10%伤害");
        add(getCommonText("rotten", 2), "生命值低于50%时降低5%移动速度, 被击中时会使阴影之雨从天而降");
        add(SHATTERED_COMMUNITY.get(), "幻灭心元石");
        add(getCommonText("shattered", 1), "幻灭于不可知的仇恨中，它仍然包含着归一心元石大部分的力量……");
        add(getCommonText("shattered", 2), "每10s回复已损生命值15%的生命");
        add(getCommonText("shattered", 3), "造成伤害时会使你获得怒气值，该效果与其的防御属性无关");
        add(getCommonText("shattered", 4), "怒气模式激活时，获得的怒气值会减半");
        add(getCommonText("shattered", 5), "在怒气模式下造成伤害能够进一步增加怒气模式的伤害加成");
        add(getCommonText("shattered", 6), "当前增幅等级: %d");
        add(getCommonText("shattered", 7), "距离下一等级: %d%%");
        add(getCommonText("shattered", 8), "总怒气模式伤害加成: %d%%");
        add(ClientInteraction.KEY_GROUP, "灾厄饰品");
        add("key.description.calamity_curios.rage_active", "怒气模式激活");
        add(getCommonText("rage_item"), "永久增加暴怒模式持续时间%d秒");
        add(MUSHROOM_PLASMA_ROOT.get(), "蘑菇根质");
        add(INFERNAL_BLOOD.get(), "地狱之血");
        add(LIGHTNING_CONTAINER.get(), "电刑之容");
        add(DARKNESS_HEART.get(), "黑暗之心");
        add(getCommonText("darkness_heart", 1), "一颗黑色的心脏，它是活的....");
        add(getCommonText("darkness_heart", 2), "你的怒气随时间增长");
        add(getCommonText("darkness_heart", 3), "怒气的获取即使处于怒气模式也不再衰减");
        add(getAttribute("critical_strike_chance"), "暴击率");
        add(ABADDON.get(), "魔鬼之庇护");
        add(EXTINCTION_VOID.get(), "终结虚空");
        add(getCommonText("abaddon", 1), "暴击会产生爆炸，并将敌人用硫磺火引燃");
        add(getCommonText("abaddon", 2), "免疫硫磺火减益");
        add(CalamityEffects.BRIMSTONE_FLAMES.get(), "硫磺火");
        add(getAttribute("damage_up"), "增伤");
        add(CALAMITY_VOID.get(), "灾劫虚空");
        add(getCommonText("calamity_void"), "被攻击时会使攻击者获得硫磺火减益");
        add(VEXATION_NECKLACE.get(), "恼怒项链");
        add(getCommonText("vexation"), "你的所有攻击都会造成酸性毒液减益");
        add(CalamityEffects.ACID_VENOM.get(), "酸性毒液");
        add(NIGHT_SOUL.get(), "暗影之魂");
        add(getCommonText("night_soul", 1), "黑暗生物的精华");
        add(LIGHT_SOUL.get(), "光明之魂");
        add(getCommonText("light_soul", 1), "光明生物的精华");
        add(SILK.get(), "丝绸");
        add(UELIBLOOM.get(), "龙蒿锭");
        add(ASCENDANT_SPIRIT_ESSENCE.get(), "化神精魄");
        add(getCommonText("essence", 1), "融合强大灵魂而制成的最高级催化剂");
        add(POLTERPLASM.get(), "灵质");
        add(getCommonText("polterplasm", 1), "可怖恶意涌动不已");
        add(NIGHTMARE_FUEL.get(), "梦魇魔能");
        add(getCommonText("nightmare_fuel", 1), "收割之月散发着诡异的光芒，它会搅乱你的心智");
        add(ENDOTHERMIC_ENERGY.get(), "恒温能量");
        add(getCommonText("energy", 1), "寒霜之月散发着明洁的光辉，它的极寒能够吸收周围的生命");
        add(DARK_SUN_FRAGMENT.get(), "日蚀之阴碎片");
        add(getCommonText("fragment", 1), "黑蚀之日蓄势待发。曜日与皎月，两种相斥天体的能量聚合进这一块晶体中");
        add(GALACTICA_SINGULARITY.get(), "星系异石");
        add(getCommonText("singularity", 1), "来自世界之外的奇异物质");
        add(VORTEX.get(), "星旋碎片");
        add(getCommonText("vortex", 1), "旋涡能量由此碎片散发而出");
        add(NEBULA.get(), "星云碎片");
        add(getCommonText("nebula", 1), "星系之力驻留于此碎片内");
        add(STARDUST.get(), "星尘碎片");
        add(getCommonText("stardust", 1), "让人目眩神迷的粒子围绕此碎片旋转");
        add(SOLAR.get(), "日耀碎片");
        add(getCommonText("solar", 1), "宇宙之怒存在于此碎片内");
        add(DESTINY_BOOK.get(), "命运之书");
        add(getCommonText("destiny", 1), "撰写了生灵的秘密");
        add(getCommonText("destiny", 2), "装备后在击杀时生物有小概率记录此生物的刷怪蛋，右键取出，不会被再次覆盖");
        add(getCommonText("destiny", 3), "击杀生物时若此对应的生物已经被记录，则微幅永久提升对此生物的伤害。取出时则移除");
        add(MELD_CONSTRUCT.get(), "冥思构造体");
        add(MELD_BLOB.get(), "冥思溶剂");
        add(SAND_SHARK.get(), "旱海鲨牙项链");
        add(REAPER.get(), "猎魂鲨牙项链");
        add(BAROCLAW.get(), "潜渊爪");
        add(getCommonText("baroclaw"), "击中你的敌怪会受到高伤害以及碎甲和深渊水压减益");
        add(CalamityEffects.CRUSH_DEPTH.get(), "深渊水压");
        add(ELDRITCH.get(), "惧魂神物");
        add(getCommonText("eldritch", 1), "提升25%弹射物速度并降低25%魔力消耗");
        add(getCommonText("eldritch", 2), "免疫死亡低语减益，攻击造成叠加的死亡低语减益，最高3级");
        add(CalamityEffects.WHISPERING_DEATH.get(), "死亡低语");
        add(AFFLICTION.get(), "灾劫之尖啸");
        add(getCommonText("affliction"), "为你和你的所有队友增加10%最大生命值、7%伤害减免、13点防御、6点的盔甲韧性和10%伤害");
        add(DIMENSIONAL.get(), "维魂神物");
        add(getCommonText("dimensional"), "所有伤害乘1.4倍，代价是所受伤害增加20%");
        add(CalamityEntity.SHADOWS_RAIN.get(), "阴影之雨");
        add(getDeath("calamity_curios.sulfur_fire"), "%s被硫磺火焚烧殆尽");
        add(getDeathPlayer("calamity_curios.sulfur_fire"), "%s被硫磺火焚烧殆尽");
        add(getDeath("calamity_curios.sink"), "%s沉沦于深渊之中");
        add(getDeathPlayer("calamity_curios.sink"), "%s沉沦于深渊之中");
        add(getCommonText("calamity_records"), "本Mod的所有唱片音乐来源均来自Terraria的Calamity和Calamity Music模组。");
        add(CALAMITY.get(), "灾厄");
        add(getCommonText("calamity", 1), "你看起来很自信，但你对接下来将要到来的痛苦一无所知");
        add(getCommonText("calamity", 2), "你享受地狱之旅么？");
        add(getCommonText("calamity_sunk"), "第一灾（沉沦）: 任何玩家的受伤都会使你承担一部分伤害。如果只有你一人则此次伤害翻倍");
        add(getCommonText("sunk_inverted"), "第一灾（反转）: 你受到的伤害减少30%");
        add(getCommonText("calamity_fire"), "第二灾（硫火）: 你受到的火焰伤害转化为真实灼烧，如果你具有防火增益，则会引爆并根据增益剩余时间和着火时间造成百分比伤害");
        add(getCommonText("fire_inverted"), "第二灾（反转）: 将火焰伤害转化为治愈量。如果你正在着火，则清算火焰时间以此增幅并治愈你");
        add(getCommonText("calamity_silva"), "第三灾（始源）: 你对任何生物造成的伤害减少30%，任何生物对你造成的伤害提高30%");
        add(getCommonText("silva_inverted"), "第三灾（反转）: 中立生物不再攻击你，大部分敌对生物在你攻击之前会完全无视你");
        add(getCommonText("calamity_abyss"), "第四灾（深渊）: 攻击会使你降低10%的移速和攻速。当你身处黑暗时，清零你的护甲与免伤");
        add(getCommonText("abyss_inverted"), "第四灾（反转）: 攻击会使你提高5%的移速和攻速。当你身处黑暗时，你的护甲效力提高50%");
        add(GIANT_SHELL.get(), "巨大甲壳");
        add(getCommonText("giant_shell"), "降低10%速度，受击后会移除速度惩罚并降低防御，持续3秒");
        add(getAttribute("close_range"), "近战伤害");
        add(CRYSTYL_CRUSHER.get(), "终极碾碎器");
        add(getCommonText("crystyl_crusher"), "更快，更深！");
        add(LIFE_JELLY.get(), "生命胶质");
        add(getCommonText("life_jelly"), "生命低于50%受击给予你生命再生效果，存在30s的冷却");
        add(CLEANSING_JELLY.get(), "纯净胶质");
        add(getCommonText("cleansing_jelly"), "存在两个及以上的减益时，清空你的减益效果，存在30s的冷却");
        add(MARNITE.get(), "合成岩斥力盾");
        add(getCommonText("marnite_repulsion_shield", 1), "背刺者要当心了!");
        add(getCommonText("marnite_repulsion_shield", 2), "背后攻击你的敌人会受到3点的无视护甲伤害");
        add(FUNGAL_SYMBIOTE.get(), "真菌共生体");
        add(getCommonText("fungal_symbiote", 1), "若你的脚下适合蘑菇生长，你的脚下会长出蘑菇");
        add(getCommonText("fungal_symbiote", 2), "食用蘑菇煲会获得与蘑共生增益");
        add(CalamityEffects.MUSHY.get(), "与蘑共生");
        add(CROWN_JEWEL.get(), "王冠宝石");
        add(getCommonText("crown_jewel"), "受到任何减益时会大幅增加自然生命再生");
        add(OCEAN_SHIELD.get(), "海之盾");
        add(getCommonText("ocean_shield"), "浸没在水中时增加4点防御");
        add(GIANT_PEARL.get(), "大珍珠");
        add(getCommonText("giant_pearl"), "光明之环环绕周身，减速周身的敌人");
        add(BEE.get(), "蜜蜂护符");
        add(getCommonText("bee", 1), "在生命值全满时基于你的伤害减免增加伤害");
        add(getCommonText("bee", 2), "在生命值全满时受到的伤害减半，减半伤害的效果有10秒冷却时间");
        add(HONEY_DEW.get(), "蜂蜜露珠");
        add(getCommonText("honey_dew", 1), "获得+1HP/5s生命再生，受到减益时再额外获得+1HP/5s生命再生，站立不动时获得+1.5HP/5s生命再生");
        add(getCommonText("honey_dew", 2), "减半受到减益的持续时间");
        add(ARCHAIC_POWDER.get(), "古元粉末");
        add(getCommonText("archaic_powder"), "处于地下或地狱时增加5%伤害减免和6点防御");
        add(RADIANT_OOZE.get(), "光泥");
        add(getCommonText("radiant_ooze"), "基于失去的生命值获得不同程度的生命再生");
        add(CalamityEffects.GLACIAL_STATE.get(), "冰河时代");
        add(FROST_BARRIER.get(), "寒冰屏障");
        add(getCommonText("frost_barrier"), "你受击时会冻结附近的敌人，免疫冰冻伤害");
        add(URSA_SERGEANT.get(), "大熊座雀鲷");
        add(getCommonText("ursa_sergeant", 1), "使你免疫幻星感染和野性咬噬减益");
        add(getCommonText("ursa_sergeant", 2), "生命值较低时获得生命再生");
        add(GIANT_TORTOISE_SHELL.get(), "巨大龟壳");
        add(AMALGAMATED_BRAIN.get(), "融合之脑");
        add(getCommonText("amalgamated_brain", 1), "被击中时会使阴影之雨从天而降");
        add(getCommonText("amalgamated_brain", 2), "使你获得闪避攻击的能力");
        add(getCommonText("amalgamated_brain", 3), "低于2的伤害的攻击不会触发闪避");
        add(getCommonText("amalgamated_brain", 4), "根据被闪避的攻击伤害，闪避有15到90秒的冷却时间");
        add(getCommonText("amalgamated_brain", 5), "闪避攻击后会使你获得暴击率加成");
        add(getCommonText("amalgamated_brain", 6), "受到攻击时会对敌人造成困惑减益");
        add(REGENATOR.get(), "再生护符");
        add(getCommonText("regenator"), "每秒恢复生命");
        add(BLOOM_STONE.get(), "绽花石");
        add(getCommonText("bloom_stone", 1), "远古遗物之一");
        add(getCommonText("bloom_stone", 2), "基于一天中的时间加速生命再生");
        add(getCommonText("bloom_stone", 3), "两种效果都会在午后至日落期间达到最大");
        add(getCommonText("bloom_stone", 4), "你走过的草地会百花齐放");
        add(LIVING_DEW.get(), "生命露珠");
        add(ANGELIC_ALLIANCE.get(), "圣天盟誓");
        add(getCommonText("angelic_alliance", 1), "你能对眼前的敌人做出最终审判");
        add(getCommonText("angelic_alliance", 2), "增加两个额外饰品栏和召唤印记，按下主动键获得15秒神之祝福");
        add(getCommonText("angelic_alliance", 3), "拥有圣天祝福增益时消耗所有的召唤印记，");
        add(getCommonText("angelic_alliance", 4), "每一个召唤印记都会使你获取增益");
        add(getCommonText("angelic_alliance", 5), "拥有圣天祝福增益时你会恢复此次攻击10%的生命");
        add(getCommonText("angelic_alliance", 6), "拥有圣天祝福增益时你的所有攻击都会造成放逐之火减益");
        add(INFECTED_JEWEL.get(), "疫染星石");
        add(getCommonText("infected_jewel", 1), "一颗被太空腐败玷污的漂亮宝石");
        add(getCommonText("infected_jewel", 2), "+1HP/5s生命再生");
        add(getCommonText("infected_jewel", 3), "受到任何减益时会获得8点防御和+2HP/5s生命再生");
        add(getCommonText("infected_jewel", 4), "受到任何减益时会大幅增加自然生命再生");
        add(getCommonText("infected_jewel", 5), "没有受到减益后获得的防御会快速消散");
        add(getCommonText("infected_jewel", 6), "除首个减益外每个减益额外提供2点防御");
        add(getCommonText("infected_jewel", 7), "使幻星感染减益对你不造成伤害");
        add(BLOOD_PACT.get(), "血契");
        add(getCommonText("blood_pact"), "增强任何形式的生命恢复");
        add(FLESH_TOTEM.get(), "血肉图腾");
        add(getCommonText("flesh_totem"), "受伤时大幅度减少此次伤害，有10s冷却");
        add(AMBROSIAL_AMPOULE.get(), "百草天香瓶");
        add(getCommonText("ambrosial_ampoule", 1), "基于失去的生命值获得+1~+5HP/s生命再生");
        add(getCommonText("ambrosial_ampoule", 2), "站立不动时获得+1.5HP/s生命再生");
        add(getCommonText("ambrosial_ampoule", 3), "获得+1HP/s生命再生，受到伤害性减益时再额外获得+1HP/s生命再生");
        add(getCommonText("ambrosial_ampoule", 4), "减半减益的持续时间");
        add(CalamityEffects.CONFUSED.get(), "困惑");
        add(VITAL_JELLY.get(), "活力胶质");
        add(GRAND_GELATIN.get(), "绚彩明胶");
        add(getCommonText("grand_gelatin"), "生命值低于50%时受击产生一个纯净光环，光环会净化所有减益并提供8s的较强生命再生");
        add(ABSORBER.get(), "阴阳吸星石");
        add(getCommonText("absorber", 1), "击中你的敌怪会受到极高伤害以及一个显著增加受到伤害的减益");
        add(getCommonText("absorber", 2), "生命值低于50%时受击产生一个纯净光环,光环会净化所有减益");
        add(getCommonText("absorber", 3), "光环附加所有玩家的生命再生，伤害和伤害减免提升，持续10秒，有30秒的冷却");
        add(getCommonText("absorber", 4), "吸收敌人攻击5%的伤害并将其转化为对你的治疗");
        add(CalamityEffects.RE_GENA.get(), "新生律动");
        add(CalamityEffects.NATURE_PAIN.get(), "吸尽之痛");
        add(getDeathPlayer("counter_injury"), "被自己杀死了");
        add(getDeath("counter_injury"), "被自己杀死了");
        add(DEIFIC_AMULET.get(), "神圣护身符");
        add(getCommonText("deific_amulet", 1), "受到伤害时会召唤星星从天而降并延长受伤后无敌时间");
        add(getCommonText("deific_amulet", 2), "根据你已损失的生命值在受伤时获得额外的无敌帧");
        add(getCommonText("deific_amulet", 3), "满血时提供10无敌帧，最高提升至25%以下血量时的40无敌帧");
        add("key.description.calamity_curios.crystallization", "渎火核心格挡");
        add(BLAZING_CORE.get(), "渎火核心");
        add(getCommonText("blazing_core", 1), "亵渎天神的炽热之心");
        add(getCommonText("blazing_core", 2), "按下渎火核心格挡会将你包裹在亵渎水晶中，并激活一次格挡");
        add(getCommonText("blazing_core", 3), "包裹后短时间内受击会使水晶破碎, 水晶破碎时，攻击周围所有敌人且你免疫这次伤害");
        add(getCommonText("blazing_core", 4), "破碎后，此伤害减免效果将进入冷却");
        add(getCommonText("blazing_core", 5), "处于冷却期间时如果水晶再次破碎，水晶将会消失，并治愈你");
        add(getCommonText("blazing_core", 6), "处于冷却期间时受击伤害不会降低");
        add(BLOODFLARE_CORE.get(), "血炎晶核");
        add(getCommonText("bloodflare_core", 1), "受到防御损伤时会缓慢治疗你");
        add(getCommonText("bloodflare_core", 2), "每恢复1点防御便为你回复1点生命值");
        add(getCommonText("bloodflare_core", 3), "受到伤害时会损失至少一半的防御");
        add("block.calamity_curios.light", "光照方块");
        add(EVOLUTION.get(), "进化者");
        add(getCommonText("evolution", 1), "你会反弹来犯的弹射物，被反弹的弹射物不会对你造成伤害");
        add(getCommonText("evolution", 2), "低于最大生命值10%伤害的弹射物不会被反弹");
        add(getCommonText("evolution", 3), "根据被反弹的弹射物伤害，反弹有最大45秒的冷却时间");
        add(getCommonText("evolution", 4), "反弹后，你会恢复本次伤害的一半和生命再生效果，持续5秒");
        add(getCommonText("evolution", 5), "再次被相同弹射物击中时，此弹射物对你造成的伤害降低15%");
        add(NEBULOUS_CORE.get(), "星云之核");
        add(getCommonText("nebulous_core", 1), "召唤漂浮的小星云保护你");
        add(getCommonText("nebulous_core", 2), "受到致死伤害时会复活并将并将生命值回复至40%");
        add(getCommonText("nebulous_core", 3), "此效果有90秒冷却时间");
        add(CalamityEntity.NEBULA.get(), "小星云");
        add(CalamityEffects.GOD_SLAYER_INFERNO.get(), "弑神怒焰");
        add(SPONGE.get(), "化棉留香石");
        add(getCommonText("sponge", 1), "投影一个至多吸收30点伤害的量子泡沫屏障");
        add(getCommonText("sponge", 2), "屏障激活时会提供15点防御并降低10%所受伤害");
        add(getCommonText("sponge", 3), "屏障会在受击后9秒开始重新充能，从0重新充能到满需要花费6秒");
        add(getCommonText("sponge", 4), "重新充能期间受击会重置充能计时器");
        add(BLOOD_GOD_CHALICE.get(), "血神圣杯");
        add(getCommonText("blood_god_chalice", 1), "竟然为了一滴血付出了这么多");
        add(getCommonText("blood_god_chalice", 2), "+2HP/5s生命再生并增强25%的瞬间治疗药水药效");
        add(getCommonText("blood_god_chalice", 3), "受到4点以上伤害时，将超出的部分转化为流血效果");
        add(getCommonText("blood_god_chalice", 4), "使用瞬间治疗药水能够抵消至多50%药水治疗量的流血伤害");
        add(getCommonText("blood_god_chalice", 5), "在流血时解除装备将会立即造成剩余伤害");
        add(getDeath("calamity_curios.blood_god"), "成为了祭品");
        add(DEITIES_RAMPART.get(), "神之壁垒");
        add(getCommonText("deities_rampart", 1), "受到伤害时会召唤星星从天而降并延长受伤后无敌时间");
        add(getCommonText("deities_rampart", 2), "根据你已损失的生命值在受伤时获得额外的无敌帧");
        add(getCommonText("deities_rampart", 3), "满血时提供10无敌帧，最高提升至25%以下血量时的40无敌帧");
        add(getCommonText("deities_rampart", 4), "受到一半生命以上伤害时提供20额外无敌帧");
        add(getCommonText("deities_rampart", 5), "生命低于50%时会在你的周围生成能够降低所受伤害的护盾");
        add(getCommonText("deities_rampart", 6), "生命值高于25%时会将团队中其他玩家所受伤害的25%转移到佩戴者身上");
        add(getDeath("calamity_curios.magic_projectile"), "被魔法弹幕击碎了");
        add("key.description.calamity_curios.adrenaline_active", "肾上腺素激活");
        add(DRAEDON_HEART.get(), "嘉登之心");
        add(getCommonText("draedon_heart", 1), "纳米机器，小子");
        add(getCommonText("draedon_heart", 2), "可以激活肾上腺素条或纳米机器条");
        add(getCommonText("draedon_heart", 3), "与肾上腺素不同，你在受到伤害时不会失去纳米机器条而是停止充能1秒");
        add(getCommonText("draedon_heart", 4), "在完全充能时，按下激活按键会在3秒内逐渐回复90%的生命值");
        add(getCommonText("draedon_heart", 5), "回复生命值时，降低50%所受伤害");
        add(getCommonText("draedon_heart", 6), "Mode: 纳米机械条");
        add(getCommonText("draedon_heart", 7), "Mode: 肾上腺素");
        add(getCommonText("adrenaline_item"), "永久增加肾上腺素20%伤害和5%伤害减免");
        add(ELECTROLYTE_GEL_PACK.get(), "电磁凝胶包");
        add(STARLIGHT_FUEL_CELL.get(), "星光能量核心");
        add(ECTOHEART.get(), "幽魂之心");
        add(CELESTIAL_ONION.get(), "天体洋葱");
        add(getCommonText("celestial_onion", 1), "外星的力量激荡在它的层叠之中");
        add(getCommonText("celestial_onion", 2), "永久增加1格饰品栏，只能使用一次");
        add(DRAGON_FRUIT.get(), "龙果");
        add(MIRACLE_FRUIT.get(), "奇迹之果");
        add(ELDER_BERRY.get(), "旧神浆果");
        add(BLOOD_ORANGE.get(), "血橙");
        add(getCommonText("blood_orange"), "它很甜，也很香");
        add(getCommonText("miracle_fruit"), "令人神清气爽，甚至好像略带薄荷的香气");
        add(getCommonText("elder_berry"), "摸上去像是土做的，尝起来酸甜香浓");
        add(getCommonText("dragon_fruit"), "尽管味道有些寡淡，但这味道绝对堪称是种全新的体验");
        add(getCommonText("life_fruit"), "永久增加25%最大生命值，仅可食用一次");
        add(HARPY_RING.get(), "女妖指环");
        add(getCommonText("harpy_ring"), "增加20%飞行时间");
        add(AERO_STONE.get(), "天蓝石");
        add(getCommonText("aero_stone", 1), "远古遗物之一");
        add(getCommonText("aero_stone", 2), "提供4s的额外飞行时间");
        add("key.description.calamity_curios.sprinting", "饰品冲刺");
        add(DEEP_DIVER.get(), "深潜者");
        add(getCommonText("deep_diver", 1), "获得短距离撞击冲刺能力");
        add(getCommonText("deep_diver", 2), "此冲刺可以在不受伤害的情况下猛击穿过敌怪而且可以快速连续使用");
        add(getCommonText("deep_diver", 3), "极大提高水下移动力");
        add(ORNATE_SHIELD.get(), "宝光盾牌");
        add(getCommonText("ornate_shield", 1), "获得撞击冲刺能力");
        add(getCommonText("ornate_shield", 2), "此冲刺可以在不受伤害的情况下猛击穿过敌怪");
        add(getCommonText("ornate_shield", 3), "免疫冻结伤害");
        add(ANGEL_TREADS.get(), "天使之靴");
        add(getCommonText("angel_treads", 1), "极致的速度!");
        add(getCommonText("angel_treads", 2), "增加36%加速度");
        add(getCommonText("angel_treads", 3), "增加飞行时间");
        add(getCommonText("angel_treads", 4), "在冰面上获得额外的机动性");
        add(getCommonText("angel_treads", 5), "使你获得在流体上行走的能力");
        add(getCommonText("angel_treads", 6), "使你免疫着火");
        add(ASGARD_VALOR.get(), "阿斯加德之英勇");
        add(getCommonText("asgard_valor", 1), "免疫击退和火焰");
        add(getCommonText("asgard_valor", 2), "概率免疫减益");
        add(LEVIATHAN_AMBERGRIS.get(), "利维坦的龙涎香");
        add(getCommonText("leviathan_ambergris", 1), "增加20%的冲刺速度");
        add(getCommonText("leviathan_ambergris", 2), "冲刺间隔减少33%");
        add(getCommonText("leviathan_ambergris", 3), "你的冲刺会被水赋能，使用粘稠水流击退并伤害附近的敌人");
        add(GRAVISTAR_SABATON.get(), "引力靴");
        add("key.description.calamity_curios.slam", "引力靴猛击");
        add(getCommonText("gravistar_sabaton", 1), "增加20%跳跃高度");
        add(getCommonText("gravistar_sabaton", 2), "免疫摔落伤害");
        add(getCommonText("gravistar_sabaton", 3), "在半空中按引力靴猛击进行一次极速猛击");
        add(getCommonText("gravistar_sabaton", 4), "一旦接触到地面你就会在脚下产生爆炸");
        add(getCommonText("gravistar_sabaton", 5), "加速度越快，爆炸的伤害越高，范围越大");
        add(getCommonText("gravistar_sabaton", 6), "猛击到地面后会暂时增加100%跳跃高度");
        add(BRIMSTONE_LOCUS.get(), "硫火魔珠");
        add(getCommonText("brimstone_locus", 1), "我不仅可以用强大的魔法增强你的装备，还可以引出某些物品真正的死灵之力...");
        add(CalamityEffects.GRUESOME_EVIL_SPIRITS.get(), "腥邪诡灵");
        add(GRUESOME_EMINENCE.get(), "异端僭越");
        add("key.description.calamity_curios.gruesome_eminence", "异端僭越激活");
        add(getCommonText("gruesome_eminence", 1), "聚合成那地牢怪物的灵魂永远无法进入他们所期望的来世，");
        add(getCommonText("gruesome_eminence", 2), "被愤怒玷污、融化，他们终将如此。");
        add(getCommonText("gruesome_eminence", 3), "按下主动按键，召唤一团腥邪诡灵附身于你，你造成的攻击会大幅提高，");
        add(getCommonText("gruesome_eminence", 4), "但随着时间的流逝你的身体会逐渐不受控制");
        add(SHIELD_OF_THE_HIGH_RULER.get(), "至高统治之盾");
        add(getCommonText("shield_of_the_high_ruler", 1), "为了王国的命运!");
        add(getCommonText("shield_of_the_high_ruler", 2), "小概率使你免疫减益");
        add(getCommonText("shield_of_the_high_ruler", 3), "使你获得强化的克苏鲁护盾冲刺能力");
        add(getCommonText("shield_of_the_high_ruler", 4), "撞击敌人会缩短50%再次冲刺的所需时间");
        add(getCommonText("shield_of_the_high_ruler", 5), "如果弹幕从正面击中你，它造成的伤害降低15%");
        add(STATIS_NINJA_BELT.get(), "斯塔提斯的忍者腰带");
        add(STATIS_VOID_SASH.get(), "斯塔提斯的虚空饰带");
        add(getCommonText("statis_ninja_belt", 1), "增加32%跳跃高度并允许自动跳跃");
        add(getCommonText("statis_ninja_belt", 2), "获得较高的摔落伤害抗性");
        add(getCommonText("statis_void_sash", 2), "免疫摔落伤害");
        add(getCommonText("statis_ninja_belt", 3), "可以攀爬、冲刺和闪避攻击");
        add(getCommonText("statis_ninja_belt", 4), "低于2的伤害不会触发闪避");
        add(getCommonText("statis_ninja_belt", 5), "根据被闪避的攻击伤害，闪避有15到90秒的冷却时间");
        add(CalamityEffects.DODGE_CD.get(), "闪避冷却");
        add(ELYSIAN_AEGIS.get(), "极乐之庇护");
        add(getCommonText("elysian_aegis"), "被亵渎之火所祝福的盾牌");
        add(getCommonText("elysian_aegis", 1), "获得被圣火加强的撞击冲刺能力");
        add(getCommonText("elysian_aegis", 2), "此冲刺可以猛击穿过敌怪但不受伤害");
        add(getCommonText("elysian_aegis", 3), "免疫击退和火焰");
        add(getCommonText("elysian_aegis", 4), "免疫硫磺火，龙焰减益");
        add(SpellType.AFLAME.getType(), "魔焱");
        add(SpellType.AFLAME.getDescription(), "攻击会点燃目标，但概率反射于自身");
        add(SpellType.EPHEMERAL.getType(), "须臾");
        add(SpellType.EPHEMERAL.getDescription(), "连续使用时伤害会持续降低。停止使用时，伤害会逐渐恢复。刚开始使用时它会造成比正常情况下高得多的伤害。");
        add(SpellType.WITHERED.getType(), "凋零");
        add(SpellType.WITHERED.getDescription(), "当你受伤，会根据之前累计造成的伤害恢复一定比例的生命值，最高可达100%。随后，你会持续受到减益伤害，但你造成的伤害会上升。");
        add(SpellType.RESENTFUL.getType(), "憎懣");
        add(SpellType.RESENTFUL.getDescription(), "使弹幕的伤害取决于目标与你的距离，距离越远，伤害越高。反之亦然。");
        add(SpellType.BLOODTHIRSTY.getType(), "嗜血");
        add(SpellType.BLOODTHIRSTY.getDescription(), "使弹幕的伤害取决于目标与你的距离，距离越近，伤害越高。反之亦然。");
        add(SpellType.PERSECUTED.getType(), "压迫");
        add(SpellType.PERSECUTED.getDescription(), "当攻击时，或随着时间推移，你的附近会生成一个恶魔之门，并在一小段时间后生成恶魔。如果恶魔出现之前传送门被严重破坏，恶魔们会选择攻击敌怪；否则，当传送门消失后，恶魔们就会选择攻击玩家。");
        add(SpellType.LECHEROUS.getType(), "淫欲");
        add(SpellType.LECHEROUS.getDescription(), "生成一个硫磺怪物处于你和你的鼠标中间，干扰你的武器发射的弹幕。硫磺怪物死亡后会释放很多红心。");
        add(SpellType.TAINTED.getType(), "邪染");
        add(SpellType.TAINTED.getDescription(), "取消该物品的弹幕，在挥舞武器时，两只额外的骷髅手臂会与你一起挥舞武器。");
        add(SpellType.OBLATORY.getType(), "献奉");
        add(SpellType.OBLATORY.getDescription(), "减少魔力消耗并大幅增加伤害，但使用该物品偶尔会消耗你的生命值。");
        add(SpellType.TRAITOROUS.getType(), "背叛");
        add(SpellType.TRAITOROUS.getDescription(), "当你的魔力值低于25%时，使用该武器会立刻消耗你的全部魔力值并生成一个无差别攻击一切生物的怪物。");
        add(SpellType.INDIGNANT.getType(), "愤慨");
        add(SpellType.INDIGNANT.getDescription(), "使用时召唤一个恶魔攻击你，但恶魔死亡后会产生治愈射线治疗你。");
        add(SpellType.HELLBOUND.getType(), "狱使");
        add(SpellType.HELLBOUND.getDescription(), "召唤物会在生成40秒后产生剧烈爆炸并消失。在这40秒内，召唤物存在时间越久，造成的伤害越高，并且会随机产生小范围爆炸。");
        add(SpellType.EXHUMED.getType(), "死灵炼注");
        add(SpellType.EXHUMED.getDescription(), "将该物品转化为更加强大的物品");
        add("key.description.calamity_curios.enchant", "咒术炼注");
        add(CalamityEffects.VULNERABILITY_HEX.get(), "硫磺火咒");
        add(CalamityEffects.APOPTOSIS.get(), "凋亡");
        add(ASCENDANT_INSIGNIA.get(), "进升证章");
        add(getCommonText("ascendant_insignia", 1), "飞行时间增加30%");
        add(getCommonText("ascendant_insignia", 2), "按下主动键会给予你飞升之力，提供8秒的无限飞行时间");
        add(getCommonText("ascendant_insignia", 3), "飞升有40秒冷却时间");
        add("key.description.calamity_curios.insignia_fly", "进升证章飞行");
        add(OLD_DUKE_SCALES.get(), "硫海遗爵之鳞");
        add(getCommonText("old_duke_scales", 1), "出现一个耐力指示器");
        add(getCommonText("old_duke_scales", 2), "使用任何冲刺会消耗20%耐力");
        add(getCommonText("old_duke_scales", 3), "不进行冲刺后1.5秒，耐力会逐渐恢复到100%");
        add(getCommonText("old_duke_scales", 4), "静止时耐力恢复地更快");
        add(getCommonText("old_duke_scales", 5), "如果耐力降到0%，你会进入疲惫状态");
        add(getCommonText("old_duke_scales", 6), "此状态会一直持续到耐力再次恢复至100%");
        add(ETERNITY.get(), "恒");
        add(getCommonText("eternity", 1), "书内有张白发魔女图片");
        add(getCommonText("eternity", 2), "向附近敌人施咒，令它们的生命在华丽的炫光中消逝");
        add(CRIMSON_FLASK.get(), "猩红药瓶");
        add(getCommonText("crimson_flask", 1), "处于下界时增加4%伤害减免和6点防御");
        add(getCommonText("crimson_flask", 2), "使你免疫缓慢减益");
        add(CORRUPT_FLASK.get(), "腐化药瓶");
        add(getCommonText("corrupt_flask", 1), "处于主世界时增加4%伤害减免和6点防御");
        add(getCommonText("corrupt_flask", 2), "使你免疫失明减益");
        add(RANCOR.get(), "怨戾（未完成）");
        add(getCommonText("rancor", 1), "当被原谅之人尚未能饶恕自身时，");
        add(getCommonText("rancor", 2), "得到宽恕所带来的安慰也仅限于此了。");
        add(CalamityEntity.RANCOR.get(), "怨戾法环");
        add(CalamityEntity.RANCOR_LASER.get(), "怨戾光束");
        add(ASGARDIAN_AEGIS.get(), "阿斯加德之庇护");
        add(getCommonText("asgardian_aegis", 1), "获得被宇宙狱火加强的撞击冲刺能力");
        add(getCommonText("asgardian_aegis", 2), "此冲刺可以在不受伤害的情况下猛击穿过敌怪");
        add(getCommonText("asgardian_aegis", 3), "免疫击退和火块");
        add(getCommonText("asgardian_aegis", 4), "免疫绝大多数减益");
        add(UNIVERSE_SPLITTER.get(), "渊宇天基炮");
        add(getCommonText("universe_splitter", 1), "在指定位置召唤一个能量力场");
        add(getCommonText("universe_splitter", 2), "如果立场锁定了实体，会尝试禁锢它");
        add(getCommonText("universe_splitter", 3), "力场定位成功后，几条小激光会从天而降");
        add(getCommonText("universe_splitter", 4), "几秒后，湮灭死光会在力场的位置出现");
        add(getCommonText("universe_splitter", 5), "在冷却时间内使用该武器会导致它短路，对你造成伤害");
        add(getCommonText("universe_splitter", 6), "一个来自上个时代的古老人造物体，它等待着你的命令。");
        add(getCommonText("universe_splitter", 7), "这真是个糟糕的想法，但无论如何它不是你的……对吗？");
        add(CalamityEntity.USF.get(), "渊宇天基炮力场");
        add(CalamityEntity.USB.get(), "小型激光光束");
        add(CalamityEntity.USH.get(), "巨型激光光束");
        add(CalamityEntity.ETERNITY_HEX.get(), "永恒之环");
        add(CalamitySounds.ZENITH_ATTACK.getLocationLang(), "天顶弹幕");
        add(CalamitySounds.MAJOR_LOSS.getLocationLang(), "肾上腺素流失");
        add(CalamitySounds.ADRENALINE_ACTIVATE.getLocationLang(), "肾上腺素激活");
        add(CalamitySounds.NANO_ACTIVATE.getLocationLang(), "纳米机械条启动");
        add(CalamitySounds.FULL_RAGE.getLocationLang(), "怒气充能完成");
        add(CalamitySounds.FULL_ADRENALINE.getLocationLang(), "肾上腺素充能完成");
        add(CalamitySounds.RAGE_END.getLocationLang(), "怒气狂暴时间结束");
        add(CalamitySounds.RAGE_ACTIVATE.getLocationLang(), "怒气狂暴激活");
        add(CalamitySounds.ASCENDANT_ACTIVATE.getLocationLang(), "进升证章激活");
        add(CalamitySounds.ASCENDANT_OFF.getLocationLang(), "进升证章关闭");
        add(CalamitySounds.PLASMA_BOLT.getLocationLang(), "激光发射");
        add(CalamitySounds.PHANTOM_DEATH_RAY.getLocationLang(), "幻影死亡射线");
        add(CalamitySounds.LARGE_WEAPON_FIRE.getLocationLang(), "大型武器射击");
        add(EXCELSUS.get(), "宙能波纹剑");
        add(getCommonText("excelsus", 1), "发射旋转锋刃");
        add(getCommonText("excelsus", 2), "击中敌人时召唤激光束");
        add(CalamityEntity.EXCELSUS_BLUE.get(), "宙魔之纹");
        add(CalamityEntity.EXCELSUS_MAIN.get(), "宙魔之纹");
        add(CalamityEntity.EXCELSUS_PINK.get(), "宙魔之纹");
        add(CalamitySounds.EXCELSUS_RAY.getLocationLang(), "发射射线");
        add(ATARAXIA.get(), "禅心剑");
        add(getCommonText("ataraxia"), "安宁");
        add(CalamitySounds.CURSED_DAGGER_THROW.getLocationLang(), "剑刃击中");
        add(NEBULOUS_CATACLYSM.get(), "星云灾变");
        add(getCommonText("nebulous_cataclysm"), "你的手中掌握着星云法师真正的力量……");
        add(CalamityEntity.NEBULA_NOVA.get(), "星云新星");
        add(CalamityEntity.NEBULA_CLOUD_CORE.get(), "星云");
        add(CalamitySounds.NEBULA.getLocationLang(), "星云灾变发射");
        add(CalamitySounds.NEBULA_EXPLODE.getLocationLang(), "新星爆炸");
        add(GLADIATOR_LOCKET.get(), "角斗士的金锁");
        add(getCommonText("gladiator_locket", 1), "击杀敌人时会给予你生命恢复");
        add(getCommonText("gladiator_locket", 2), "你的移动速度和伤害会随着生命值的降低而增加，至多增加20%");
        add(CalamityEntity.HEAL_ORB.get(), "生命珠");
        add(FROST_FLARE.get(), "霜冻之炎");
        add(getCommonText("frost_flare", 1), "所有攻击和弹幕都会造成缓慢减益");
        add(getCommonText("frost_flare", 2), "生命值高于50%时增加10%伤害");
        add(getCommonText("frost_flare", 3), "生命值低于50%时增加20点防御");
        add(getCommonText("frost_flare", 4), "15%最大移动速度和加速度");
        add(getCommonText("frost_flare", 5), "使你获得对冷系攻击的抗性");
        add(COMMUNITY.get(), "归一心元石");
        add(getCommonText("community", 1), "提升%s%%伤害和%s%%的暴击率");
        add(getCommonText("community", 2), "增加%s%%最大生命，%s%%伤害减免和%s的防御力");
        add(getCommonText("community", 3), "增加%s%%的移动速度和%s%%的飞行时间，+%sHp/2s的生命再生");
        add(getCommonText("community", 4), "随着你击败诸多Boss会变得更加强力(已解锁%s%%)");
        add(getCommonText("community", 5), "广大玩家的精神结晶");
        add(getCommonText("community", 6), "感谢游玩本模组，如果有机会试试泰拉瑞亚以及灾厄吧!");
        add(getCommonText("community", 7), "也感谢灾厄制作组和社区使得本模组的实现成为可能!");
        add(getCommonText("community", 8), "在最早时期你会获得所有属性的微量增幅");
        add(getCommonText("community", 9), "随着游戏进程增幅更加强力");
        add(getCommonText("view"), "按下Shift查看详情");
        add(CAMPER.get(), "露营者");
        add(getCommonText("camper", 1), "除非站定不动，否则降低90%造成的伤害");
        add(getCommonText("camper", 2), "站定不动时基于手持的物品给予增益");
        add(getCommonText("camper", 3), "站定不动时在你周围生成伤害光环");
        add(getCommonText("camper", 4), "移动时会再生生命");
        add(getCommonText("camper", 5), "只有休息好才能取得战斗的胜利");
        add(DARK_SUN_RING.get(), "蚀日尊戒");
        add(getCommonText("dark_sun_ring", 1), "+0.5HP/s生命再生，增强你驯服的生物");
        add(getCommonText("dark_sun_ring", 2), "在白天下雨时+1HP/s生命再生和10点防御");
        add(getCommonText("dark_sun_ring", 3), "在白天时+2HP/s生命再生");
        add(getCommonText("dark_sun_ring", 4), "在夜晚时增加20点防御");
        add(getCommonText("dark_sun_ring", 5), "蕴含着日蚀之阴的力量");
        add(AMALGAM.get(), "聚合之脑");
        add(getCommonText("amalgam", 1), "翻倍增益药水的持续时间并且在你死后增益也不会消失");
        add(getCommonText("amalgam", 2), "被击中时会对附近的敌人造成多种疫病相关减益");
        add(COIN_OF_DECEIT.get(), "欺诈硬币");
        add(getCommonText("coin_of_deceit", 1), "触发原版暴击时有40%的概率增加30%的本次暴击伤害");
        add(getCommonText("coin_of_deceit", 2), "为什么硬币的概率不是一半呢?");
        add(CalamityEntity.JEWEL_SPIKE.get(), "潜遁者宝石钉");
        add(SCUTTLERS_JEWEL.get(), "潜遁者宝石");
        add(getCommonText("scuttlers_jewel", 1), "受击后破碎，并产生一些宝石");
        add(getCommonText("scuttlers_jewel", 2), "对攻击者及其周围敌对生物脚下生产一个反击的钉刺");
        add(RAIDERS_TALISMAN.get(), "掠夺者护符");
        add(getCommonText("raiders_talisman", 1), "增加6%的原版暴击概率");
        add(getCommonText("raiders_talisman", 2), "增加2级抢夺等级");
        add(ROTTEN_DOG_TOOTH.get(), "腐烂犬齿");
        add(getCommonText("rotten_dog_tooth"), "使原版暴击攻击造成粉碎减益并多造成8%伤害");
        add(INK_BOMB.get(), "墨水炸弹");
        add(getCommonText("ink_bomb", 1), "受到伤害时会投掷出数枚会爆炸成墨水云雾的墨汁炸弹");
        add(getCommonText("ink_bomb", 2), "被击中时会回复部分生命");
        add(getCommonText("ink_bomb", 3), "此效果有20秒冷却时间");
        add(SILENCING_SHEATH.get(), "寂静刀鞘");
        add(getCommonText("silencing_sheath"), "潜行且在背后攻击无防备的敌人时，本次攻击翻倍");
        add(BLOODSTAINED_GLOVE.get(), "血染手套");
        add(getCommonText("bloodstained_glove"), "原版暴击会附带8点护甲穿透并为你回复2点生命值");
        add(FILTHY_GLOVE.get(), "污秽手套");
        add(getCommonText("filthy_glove"), "原版暴击会附带8点护甲穿透并额外造成8%伤害");
        add(FEATHER_CROWN.get(), "天羽头冠");
        add(getCommonText("feather_crown", 1), "增加15%弹幕速度");
        add(getCommonText("feather_crown", 2), "原版暴击会使目标漂浮");
        add(getCommonText("feather_crown", 3), "从高处坠落时获得缓降效果");
        add(MIRAGE_MIRROR.get(), "幻影魔镜");
        add(getCommonText("mirage_mirror", 1), "降低敌人的攻击性");
        add(getCommonText("mirage_mirror", 2), "站定不动时增加25%原版暴击率，移动时增加12%原版暴击率");
        add(getCommonText("mirage_mirror", 3), "使你周围光线扭曲");
        add(CORROSIVE_SPINE.get(), "腐蚀脊椎");
        add(getCommonText("corrosive_spine", 1), "在击中敌人时施加中毒减益");
        add(getCommonText("corrosive_spine", 2), "受到伤害时会释放毒云");
        add(ELECTRICIANS_GLOVE.get(), "电击手套");
        add(getCommonText("electricians_glove", 1), "原版暴击会时会释放闪电");
        add(getCommonText("electricians_glove", 2), "同时也会附带8点护甲穿透、额外造成8%伤害并为你回复2点生命值");
        add(RUIN_MEDALLION.get(), "毁灭勋章");
        add(getCommonText("ruin_medallion", 1), "允许你在疾跑时触发暴击");
        add(getCommonText("ruin_medallion", 2), "增加6%原版暴击伤害和原版暴击率");
        add(VAMPIRIC_TALISMAN.get(), "吸血鬼符咒");
        add(getCommonText("vampiric_talisman", 1), "触发原版暴击时会吸血");
        add(getCommonText("vampiric_talisman", 2), "增加12%原版暴击伤害");
        add(PRECISION_GLOVE.get(), "精准手套");
        add(getCommonText("precision_glove"), "降低15%攻速，但增加10%原版暴击伤害、15%原版暴击率和15%弹幕速度");
        add(RECKLESSNESS_GLOVE.get(), "鲁莽手套");
        add(getCommonText("recklessness_glove", 1), "增加15%攻速，但降低10%原版暴击伤害、5%原版暴击率");
        add(getCommonText("recklessness_glove", 2), "弹幕会产生偏离，偏移量取决与你的弹幕初速度");
        add(CalamityEffects.EUTROPHICATION.get(), "富营养化");
        add(ABYSSAL_MIRROR.get(), "深渊魔镜");
        add(getCommonText("abyssal_mirror", 1), "大幅度降低敌人的攻击性");
        add(getCommonText("abyssal_mirror", 2), "站定不动时增加25%原版暴击率，移动时增加12%原版暴击率");
        add(getCommonText("abyssal_mirror", 3), "使你获得闪避攻击的能力，闪避攻击时会释放伤害性药水云并眩晕附近的敌人");
        add(getCommonText("abyssal_mirror", 4), "低于最大生命值5%伤害的攻击不会触发闪避");
        add(getCommonText("abyssal_mirror", 5), "根据被闪避的攻击伤害，闪避有15到90秒的冷却时间");
        add(getCommonText("abyssal_mirror", 6), "闪避攻击时会使你下次原版暴击率大幅提升，该冷却时间与其他的闪避或反弹效果共享");
        add(getCommonText("abyssal_mirror", 7), "光无法到达海洋深处");
        add(ETHEREAL_EXTORTER.get(), "虚空掠夺者");
        add(getCommonText("ethereal_extorter", 1), "增加8%原版暴击伤害和5%原版暴击率");
        add(getCommonText("ethereal_extorter", 2), "触发原版暴击时将下一次攻击视为虚空伤害");
        add(CalamityEffects.PLAGUE.get(), "瘟疫");
        add(PLAGUE_FUEL_PACK.get(), "瘟疫燃料背包");
        add(getCommonText("plagued_fuel_pack", 1), "增加8%原版暴击伤害和15%弹幕速度以及10%原版暴击率");
        add(getCommonText("plagued_fuel_pack", 2), "在鞘翅滑翔时，按下跳跃键喷射，给予你一个加速度，并在沿途留下瘟疫毒云");
        add(getCommonText("plagued_fuel_pack", 3), "瘟疫毒云的生成有2秒冷却时间");
        add(DARK_MATTER_SHEATH.get(), "暗物质剑鞘");
        add(getCommonText("dark_matter_sheath", 1), "增加6%原版暴击率，移动时再增加10%");
        add(getCommonText("dark_matter_sheath", 2), "增加6%原版暴击伤害，允许你在疾跑时触发暴击");
        add(getCommonText("dark_matter_sheath", 3), "每10s强化你的下一次攻击，伤害翻倍");
        add(getAttribute("magic_reduction"), "法力减免");
        add(getCommonText("mana_potion"), "饮用后恢复%s点魔力值");
        add(getCommonText("mana_potion", 1), "不会获得魔力疾病减益");
        add(CalamityEffects.PLENTY_SATISFIED.get(), "很满意");
        add(HADAL_STEW.get(), "乱渊炖");
        add(getCommonText("hadal_stew", 1), "所有属性中幅提升");
        add(getCommonText("hadal_stew", 2), "恢复6点生命值与100的法力值");
        add(CalamityEffects.MAGIC_POWER.get(), "魔能");
        add(CalamityEffects.MANA_REGENERATION.get(), "魔力再生");
        add(AUREUS_CELL.get(), "星舰电池");
        add(getCommonText("aureus_cell"), "增加150点法力值，并使你获得魔力再生和魔能增益");
        add(CalamityEffects.GRAPE_BEER.get(), "葡萄啤酒");
        add(GRAPE_BEER.get(), "葡萄啤酒");
        add(getCommonText("beer_harmful"), "饮用三种以上的酒或许对你的肝脏不太好");
        add(getCommonText("grape_beer", 1), "降低3%防御和7%的速度，持续15秒");
        add(getCommonText("grape_beer", 2), "恢复7点生命值与100的法力值");
        add(MARGARITA.get(), "玛格丽塔酒");
        add(CalamityEffects.MARGARITA.get(), "玛格丽塔酒");
        add(getCommonText("margarita", 1), "减半大多数减益的持续时间");
        add(getCommonText("margarita", 2), "降低5点防御和2点韧性");
        add(getCommonText("margarita", 3), "恢复14点生命值与200的法力值");
        add(RED_WINE.get(), "红葡萄酒");
        add(getCommonText("red_wine"), "恢复大量生命，但会使你感到饥饿");
        add(WHITE_WINE.get(), "白葡萄酒");
        add(getCommonText("white_wine"), "恢复大量魔力并增强法术强度，但会削弱你的护甲与生命");
        add(CalamityEffects.WHITE_WINE.get(), "白葡萄酒");
        add(CalamityEffects.TRIPPY.get(), "幻菇中毒");
        add(ODD_MUSHROOM.get(), "怪异蘑菇");
        add(getCommonText("odd_mushroom", 1), "使你看到周围造物栩栩如生的幻像");
        add(getCommonText("odd_mushroom", 2), "致幻");
        add(getCommonText("odd_mushroom", 3), "警告：有极少数的人在观看一些视觉影像时可能会突然癫痫发作，这些影像包括电子游戏中出现的闪光或图形。如果您或您的家人有癫痫史，请在使用本菇前先与医生咨询。");
        add(getEffectText("trippy"), "你看到了世界的本质……同时增加50%伤害");
        add(getEffectText("freeze"), "增加30点防御、30%伤害减免、90%冰霜法术抗性，但是……");
        add(getEffectText("god_slayer_inferno"), "你的血肉在燃烧");
        add(getEffectText("astral_infection"), "你的血肉正在被幻星熔蚀");
        add(getEffectText("curse_inferno"), "正在损失生命值");
        add(getEffectText("elemental_mix"), "优美的元素交响曲正在剥离你的生命");
        add(getEffectText("irradiated"), "你的皮肤正被侵蚀");
        add(getEffectText("electrified"), "一动就痛!");
        add(getEffectText("mana_burn"), "过多的魔力正在烧蚀你的身心");
        add(getEffectText("crush_depth"), "被深海水压粉碎");
        add(getEffectText("dragon_burn"), "被咆哮的火焰吞没");
        add(getEffectText("mana_sickness"), "法术强度降低90%");
        add(getEffectText("crumbling"), "你的护甲损伤了");
        add(getEffectText("riptide"), "被强力水浪鞭打");
        add(getEffectText("brimstone_flames"), "焚烧身心");
        add(getEffectText("acid_venom"), "正在损失生命值");
        add(getEffectText("whispering_death"), "死亡临近；攻击力和速度降低");
        add(getEffectText("glacial_state"), "降低移动速度和和冰系法术抗性");
        add(getEffectText("mushy"), "增加防御，每两秒恢复生命值");
        add(getEffectText("confused"), "控制逆转");
        add(getEffectText("re_gena"), "你被顶尖的自然力量所祝福");
        add(getEffectText("nature_pain"), "该死的大自然，你真可怕！");
        add(getEffectText("dodge_cd"), "你的闪避暂时失效");
        add(getEffectText("vulnerability_hex"), "火焰灼烧着你的身体");
        add(getEffectText("apoptosis"), "死亡临近");
        add(getEffectText("eutrophication"), "过多的营养物质拖慢了你的步伐");
        add(getEffectText("plague"), "从内部腐烂");
        add(getEffectText("plenty_satisfied"), "所有属性大幅提升");
        add(getEffectText("mana_regeneration"), "法力再生速度提高");
        add(getEffectText("magic_power"), "法术强度提高");
        add(getEffectText("grape_beer"), "降低防御力和移动速度");
        add(getEffectText("margarita"), "降低防御力");
        add(getEffectText("white_wine"), "提高法术强度，但降低防御力和生命恢复速度");
        add(BAGUETTE.get(), "法棍");
        add(getCommonText("baguette", 1), "所有属性小幅提升");
        add(getCommonText("baguette", 2), "红葡萄酒会回复更多生命值但同时也会感到更饥饿");
        add(getCommonText("baguette", 3), "我骑上去了!");
        add(CalamityEffects.WELL_FED.get(), "吃得好");
        add(getEffectText("well_fed"), "所有属性小幅提升");
        add(CalamityEffects.BAGUETTE.get(), "法棍");
        add(getEffectText("baguette"), "和红酒绝配");
        add(DELICIOUS_MEAT.get(), "美味冻肉");
        add(getCommonText("delicious_meat"), "太好吃了");
        add(BLASPHEMOUS_DONUT.get(), "亵渎甜甜圈");
        add(getCommonText("blasphemous_donut"), "完甜不用点心，它是可以吃的");
        add(CalamityEffects.EXQUISITELY_STUFFED.get(), "酒足饭饱");
        add(getEffectText("sated"), "所有属性大幅提升");
        add(LAVA_CHICKEN_BROTH.get(), "熔岩鸡肉煲");
        add(getCommonText("lava_chicken_broth"), "真是好吃的要命!");
        add(CalamityEffects.ANECHOIC_COATING.get(), "吸音涂层");
        add(getEffectText("anechoic_coating"), "深渊生物的探测范围缩小");
        add(ANECHOIC_COATING.get(), "吸音涂层");
        add(getCommonText("anechoic_coating"), "削减深渊生物的探测能力");
        add(CalamityEffects.BOUNDING.get(), "弹跳助力");
        add(getEffectText("bounding"), "增加跳跃高度、跳跃速度和摔落伤害减免");
        add(BOUNDING.get(), "弹跳药水");
        add(getCommonText("bounding"), "增加40%摔落伤害抗性和30%跳跃高度");
        add(CalamityEffects.CALCIUM.get(), "钙质补充");
        add(getEffectText("calcium"), "免疫摔落伤害");
        add(CALCIUM.get(), "钙质药水");
        add(getCommonText("calcium"), "使你免疫摔落伤害");
        add(CalamityEffects.TESLA.get(), "特斯拉电球");
        add(getEffectText("tesla"), "召唤一个电流光环");
        add(TESLA.get(), "特斯拉药水");
        add(getCommonText("tesla"), "召唤一个会电击并减速敌人的电场");
        add(CalamityEffects.GALVANIC_CORROSION.get(), "电偶腐蚀");
        add(getEffectText("galvanic_corrosion"), "你的四肢正被腐蚀");
        add(CalamityEntity.TESLA_AURA.get(), "特斯拉光环");
        add(ZERG.get(), "虫潮药水");
        add(getCommonText("zerg"), "大幅度增加敌怪生成率");
        add(CalamityEffects.ZERG.get(), "虫潮");
        add(getEffectText("zerg"), "大幅提高刷怪率");
        add(ZEN.get(), "禅定药水");
        add(getCommonText("zen"), "大幅度降低敌怪生成率");
        add(CalamityEffects.ZEN.get(), "禅定");
        add(getEffectText("zen"), "大幅降低刷怪率");
        add(CalamityEffects.PHOTOSYNTHESIS.get(), "光合作用");
        add(getEffectText("photosynthesis"), "站在阳光下，阳光会治愈你");
        add(PHOTOSYNTHESIS.get(), "光合药水");
        add(getCommonText("photosynthesis"), "被太阳照射会健康会缓慢恢复");
        add(CalamitySounds.SUPREME_CALAMITAS.getLocationLang(), "至尊灾厄");
        add(CalamityEffects.ASTRAL_INJECTION.get(), "星幻注射");
        add(getEffectText("astral_injection"), "持续受到伤害并大幅增加魔力值恢复速度");
        add(getDeath("calamity_curios.astral_injection"), "%s的血管由于药物过量爆裂了");
        add(ASTRAL_INJECTION.get(), "星幻注射剂");
        add(getCommonText("astral_injection"), "对你造成伤害并使你获得魔力疾病减益，但是你的魔力会快速恢复");
        add(CalamityEffects.CEASELESS_HUNGER.get(), "无尽空虚");
        add(getEffectText("ceaseless_hunger"), "你吸收着世界上所有的物品");
        add(CEASELESS_HUNGER.get(), "无尽吞噬药水");
        add(getCommonText("ceaseless_hunger"), "使你将全世界的物品吸入囊中");
        add(CalamityEffects.OMNISCIENCE.get(), "全知");
        add(getEffectText("omniscience"), "你能看透世间万物。 当然，不要干坏事");
        add(OMNISCIENCE.get(), "全知药水");
        add(getCommonText("omniscience"), "高亮附近的敌人、敌人弹幕、矿石和宝藏");
        add(CalamityEntity.LUNAR_FLARE.get(), "月耀");
        add(MOONSTONE_CROWN.get(), "月长石头冠");
        add(getCommonText("moonstone_crown", 1), "增加15%弹幕速度");
        add(getCommonText("moonstone_crown", 2), "原版暴击在击中敌人时会召唤月亮耀斑");
        add(BLUNDER_BOOSTER.get(), "悖论增幅器");
        add(getCommonText("blunder_booster", 1), "增加12%原版暴击伤害和15%弹幕速度");
        add(getCommonText("blunder_booster", 2), "增加10%原版暴击率");
        add(getCommonText("blunder_booster", 3), "召唤一个红色的闪电光环包围玩家并电击附近的敌人");
        add(getCommonText("blunder_booster", 4), "允许你进行鞘翅飞行");
        add(getCommonText("blunder_booster", 5), "按下跳跃键消耗能量来飞行冲刺");
        add(getCommonText("blunder_booster", 6), "此效果有0.5秒冷却时间，不在飞行时能量会缓慢恢复");
        add(CINNAMON_SOLYN.get(), "索琳肉桂卷");
        add(getCommonText("cinnamon_solyn"), "这种巨星级甜美的来源是我的冠名!");
        add(CalamityEffects.STAR_STRIKINGLY_SATIATED.get(), "饱如巨星");
        add(getEffectText("star_strikingly_satiated"), "所有属性爆炸提升，每隔一段时间恢复自身生命");
        add(CalamityEffects.CHAOS_STATE.get(), "混沌状态");
        add(getEffectText("chaos_state"), "混沌传送被禁止使用!");
        add(SPECTRAL_VEIL.get(), "幽灵披风");
        add(getCommonText("spectral_veil", 1), "按下主动按键，向视线方向进行中距离传送");
        add(getCommonText("spectral_veil", 2), "在无敌时间内闪避攻击时会使你的下一次攻击必定触发原版暴击");
        add(getCommonText("spectral_veil", 3), "受到混沌状态减益的影响时无法进行传送");
        add(getCommonText("spectral_veil", 4), "增加15%原版暴击率");
        add(getCommonText("spectral_veil", 5), "披风里面布满了尖牙利齿……");
        add(VENERATED_LOCKET.get(), "敬天神盗盒");
        add(getCommonText("venerated_locket", 1), "增加10%原版暴击伤害");
        add(getCommonText("venerated_locket", 2), "弹射物命中时，会召唤一个复制品从天而降");
        add(getCommonText("venerated_locket", 3), "造成非弹射物伤害时，施加弑神怒焰减益");
        add(getCommonText("venerated_locket", 4), "无论你去哪儿，你总不会孤身一人");
        add("key.description.calamity_curios.spectral_teleport", "幽灵披风传送");
        add(CalamitySounds.LUNAR_FLARE.getLocationLang(), "月耀爆炸");
        add(YHARIMS_CRYSTAL.get(), "亚利姆水晶（未完成）");
        add(getCommonText("yharims_crystal"), "发射猛烈的破坏死光");
        add(FATE_THREAD.get(), "命运之绳");
        add(getCommonText("fate_thread"), "用于制作神谕卡组");
        add("curios.identifier.cards", "卡组");
        add("curios.modifiers.cards", "佩戴卡组时：");
        add(ORACLE_DECK.get(), "神谕卡组");
        add(getCommonText("oracle_deck"), "每6秒为附近所有玩家恢复4点血量。此外，它还能够让玩家单次受到的最大伤害减少至最大生命值的50%");
        add(BRILLIANCE.get(), "辉煌");
        add(getCommonText("brilliance"), "光明永驻，黑暗退散");
        add(AURA.get(), "灵光");
        add(getCommonText("aura"), "刹那顿悟，一击必杀");
        add(INSPIRATION.get(), "启迪");
        add(getCommonText("inspiration"), "灵光乍现，步履如风");
        add(ENDURANCE.get(), "坚忍");
        add(getCommonText("endurance"), "千锤百炼，不动如山");
        add(ENTITY.get(), "实体");
        add(getCommonText("entity"), "血肉为刃，疾如残影");
        add(WISDOM.get(), "智慧");
        add(getCommonText("wisdom"), "理性思考，便可取胜");
        add(METROPOLIS.get(), "都市");
        add(getCommonText("metropolis", 1), "给予你额外的迅捷潜行效果，卡组状态下会被增强");
        add(getCommonText("metropolis", 2), "繁茂宫殿，窃藏于深");
        add(RADIANCE_CARD.get(), "光芒");
        add(getCommonText("radiance_card", 1), "为玩家提升20%生命恢复");
        add(getCommonText("radiance_card", 2), "散发光芒，治愈灵魂");
        add(TEMPERANCE.get(), "克己");
        add(getCommonText("temperance"), "克制欲望，方得万众");
        add(WYRM_TOOTH_NECKLACE.get(), "幻妖龙牙项链");
        add(DEUS_CORE.get(), "星神龙核");
        add(getCommonText("deus_core", 1), "将受到的伤害转化为星辉侵蚀，在一段时间内减少对应生命值");
        add(getCommonText("deus_core", 2), "攻击可将部分星辉侵蚀转移至目标，造成更高的伤害");
        add(CMLangUtil.getDeath("astr_erosion"), "被星辉侵蚀的千疮百孔");
        add(CMLangUtil.getDeathPlayer("astr_erosion"), "被星辉侵蚀的千疮百孔");
        add(FORESEE_ORB.get(), "预知宝珠");
        add(getCommonText("foresee_orb", 1), "当玩家受到伤害超过 8 点时，本次伤害降低至 8 点，随后预知宝珠破碎并失去所有效果，进入 30 秒冷却时间。");
        add(getCommonText("foresee_orb", 2), "碎时卸下预知宝珠将对玩家造成 （90% 最大生命值） 的伤害。");
        add(getCommonText("foresee_orb", 3), "它吸取你的灵魂进行自我修复，若强行断开，你的灵魂会喷涌而出");
        add(CalamitySounds.PRISM.getLocationLang(), "棱镜射线");
        add(SACRIFICES_MASK.get(), "献祭面具");
        add(getCommonText("sacrifices_mask"), "你造成的伤害会为你恢复生命值");
        add(ABYSS_THREAD.get(), "深渊之绳");
        add(getCommonText("abyss_thread"), "用于制作堕化卡组");
        add(TAINTED_DECK.get(), "堕化卡组");
        add(CalamityEffects.DECEIVE.get(), "蒙蔽");
        add(getEffectText("deceive"), "减少移动速度");
        add(CONFUSE.get(), "迷惑");
        add(getCommonText("confuse"), "吮脑之锢");
        add(BARREN.get(), "荒芜");
        add(getCommonText("barren"), "凋零之狩");
        add(FRAIL.get(), "孱弱");
        add(getCommonText("frail"), "脆刃之锋");
        add(CalamityEffects.VOID_TOUCH.get(), "虚空之触");
        add(getCommonText("void_touch"), "你正在被虚空残蚀");
        add(NOTHING.get(), "虚无");
        add(getCommonText("nothing"), "湮灭触媒");
        add(GREED.get(), "贪婪");
        add(getCommonText("greed"), "贪欲之渊");
        add(FOOL.get(), "愚者");
        add(getCommonText("fool"), "狂智之焰");
        add(TARNISH.get(), "晦暗");
        add(getCommonText("tarnish"), "暗蚀之炎");
        add(PERPLEXED.get(), "迷茫");
        add(getCommonText("perplexed"), "乱心之速");
        add(SACRIFICE.get(), "献祭");
        add(getCommonText("sacrifice"), "血偿之力");
        add("curios.identifier.calamity", "灾厄");
        add(CalamityEffects.MOONLIGHT_SHIELD.get(), "月光护盾");
        add(getEffectText("moonlight_shield"), "皎洁的月光保护着你不受伤害");
        add(HOLY_MOONLIGHT.get(), "圣洁月光");
        add(getCommonText("holy_moonlight", 1), "装备时，为玩家提升 10% 魔法伤害，且每 30 秒提供一个不可叠加的魔力护盾。");
        add(getCommonText("holy_moonlight", 2), "魔力护盾数值等同于最大魔力值的 50% ，魔力护盾存在期间能够为玩家提升 10% 移动速度并减少 10% 魔力消耗。");
        add(getCommonText("holy_moonlight", 3), "护盾会对触碰到的敌人造成伤害，当魔力护盾被击破时，消除自身所有减益并恢复至满魔力值。");
        add(getCommonText("holy_moonlight", 4), "当没有护盾时，魔法弹幕能够吸血，玩家的当前魔力值越高，吸血量便越高。");
        add(CalamityEntity.BLACK_HOLE.get(), "黑洞");
        add(CalamityEntity.SUN.get(), "恒星");
        add(STAR_CHARM.get(), "星星符章");
        add(getCommonText("star_charm", 1), "大幅增加幸运值，召唤一个小玩意跟随着你");
        add(getCommonText("star_charm", 2), "我自己的设计！希望对你有用");
        add(PERVERSE_PURSE.get(), "人体工学钱包");
        add(getCommonText("perverse_purse", 1), "一个具有便携异空间的特殊钱包。使用时可以劫持并存储活体生物");
        add(getCommonText("perverse_purse", 2), "至多可以有三只生物被存储于钱包中");
        add(getCommonText("perverse_purse", 3), "蹲下右键可以在你所处的位置放出最后一次劫持的生物");
        add(getCommonText("perverse_purse", 4), "我通常用这个来旅行储物，轻装上阵。");
        add(getCommonText("perverse_purse", 5), "我很确信你也能找到类似的用途！");;
    }
}
